export const projectData = [
  {
    title: "Roach Hotel Booking",
    textColor: "text-white",
    image: "/projects/RoachHotelBooking.jpg",
    link1: "https://roach-hotel-booking.vercel.app/",
    link2: "https://github.com/Jkhall81/Roach-Hotel-Booking",
    direction: "right",
  },
  {
    title: "Netflix",
    textColor: "text-white",
    image: "/projects/netflix.png",
    link1: "https://melodious-lollipop-6e6ded.netlify.app/",
    link2: "https://github.com/Jkhall81/Netflix",
    direction: "left",
  },
  {
    title: "E Commer Page",
    textColor: "text-white",
    image: "/projects/Ecommerce.jpg",
    link1: "https://junk-store.vercel.app/",
    link2: "https://github.com/Jkhall81/Junk-Store",
    direction: "right",
  },
  {
    title: "Fu Donk",
    textColor: "#000000",
    image: "/projects/fudonk.jpg",
    link1: "https://fu-donk.vercel.app/",
    link2: "https://github.com/Jkhall81/Fu-Donk",
    direction: "left",
  },
  {
    title: "Hooptievana",
    textColor: "#000000",
    image: "/projects/beater2.webp",
    link1: "https://hooptievana.vercel.app/",
    link2: "https://github.com/Jkhall81/Hooptievana",
    direction: "right",
  },
  {
    title: "Wow Library",
    textColor: "text-white",
    image: "/projects/WowL.jpeg",
    link1: "https://wow-library.onrender.com/",
    link2: "https://github.com/Jkhall81/Wow-Library",
    direction: "left",
  },
];
